spring.application.name=Ebook-BE
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:ebook}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}

# Config ORM properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

# Config file upload properties
project.image=src/main/resources/static/images/
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Config Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

# Config PayOS
payos.clientId=${PAYOS_CLIENT_ID:433f43da-7ffe-42bc-890a-dc7643bea91b}
payos.apiKey=${PAYOS_API_KEY:555e2003-467e-4868-8670-ade053db8f6a}
payos.checksumKey=${PAYOS_CHECKSUM_KEY:c3a073e1e810ab979d5f7940107feae984509049ebafbf60616caac049956f02}
payos.baseReturnUrl=${PAYOS_RETURN_URL:/order/success}
payos.baseCancelUrl=${PAYOS_CANCEL_URL:/order/cancel}
# payos.clientId=${PAYOS_CLIENT_ID:...}
# payos.apiKey=${PAYOS_API_KEY:...}
# payos.checksumKey=${PAYOS_CHECKSUM_KEY:...}

